=== suryan14k/jenkins-pipeline-shared-library/api/exchange_modules/org.mule.examples/accelerator-cim-produce-library/1.2.0/jsonSchemas/AttributeSetTranslationSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/AttributeSetTranslation",
  "definitions": {
    "AttributeSetTranslation": {
      "type": "object",
      "example": {
        "attributeSet": "elit",
        "id": "fugiat non ex",
        "translatedName": "quis deserunt tempor culpa mollit",
        "auditInfo": {
          "isDeleted": null,
          "createdBy": "ut Excepteur voluptate eu",
          "updatedBy": "incididunt",
          "updatedDate": null,
          "createdDate": null
        }
      },
      "additionalProperties": true,
      "required": [
        "attributeSet",
        "id",
        "translatedName"
      ],
      "properties": {
        "id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "translatedName": {
          "type": "string"
        },
        "attributeSet": {
          "type": "string"
        },
        "auditInfo": {
          "description": "Defines standard system audit fields available for most types",
          "type": "object",
          "example": {
            "isDeleted": true,
            "createdBy": "commodo minim dolore est",
            "updatedBy": "dolor quis nulla",
            "updatedDate": "1950-01-23T19:52:29.659Z",
            "createdDate": "1950-01-23T19:52:29.659Z"
          },
          "additionalProperties": true,
          "required": [
            "isDeleted",
            "createdBy",
            "updatedBy",
            "updatedDate",
            "createdDate"
          ],
          "properties": {
            "createdDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was created"
            },
            "createdBy": {
              "type": "string",
              "description": "Identifies the system or user which created the entity"
            },
            "updatedDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was last updated"
            },
            "updatedBy": {
              "type": "string",
              "description": "Identifies the system or user which last updated the entity"
            },
            "isDeleted": {
              "anyOf": [
                {
                  "type": "boolean"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Indicates whether or not the entity has been soft-deleted"
            }
          }
        }
      }
    }
  }
}

=== suryan14k/jenkins-pipeline-shared-library/api/exchange_modules/org.mule.examples/accelerator-cim-produce-library/1.2.0/examples/AttributeSetTranslationExample.json
{
  "attributeSet": "id minim ipsum enim nisi",
  "id": null,
  "translatedName": "quis consequat",
  "auditInfo": {
    "isDeleted": null,
    "createdBy": "dolor",
    "updatedBy": "adipisicing Lorem",
    "updatedDate": "1978-08-07T17:37:11.571Z",
    "createdDate": "2005-02-26T01:31:57.369Z"
  }
}
