=== suryan14k/jenkins-pipeline-shared-library/api/exchange_modules/org.mule.examples/accelerator-cim-produce-library/1.2.0/jsonSchemas/ProductCatalogTranslationSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/ProductCatalogTranslation",
  "definitions": {
    "ProductCatalogTranslation": {
      "type": "object",
      "example": {
        "id": "minim do amet id",
        "translatedName": "Duis ea Excepteur labore"
      },
      "additionalProperties": true,
      "required": [
        "id",
        "translatedName"
      ],
      "properties": {
        "id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "productCatalog": {
          "type": "array",
          "items": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "object",
                "additionalProperties": true,
                "required": [
                  "id",
                  "name",
                  "activeFromDate"
                ],
                "properties": {
                  "id": {
                    "anyOf": [
                      {
                        "type": "string"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "name": {
                    "type": "string"
                  },
                  "activeToDate": {
                    "anyOf": [
                      {
                        "type": "string",
                        "format": "date"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "activeFromDate": {
                    "type": "string",
                    "format": "date"
                  },
                  "auditInfo": {
                    "description": "Defines standard system audit fields available for most types",
                    "type": "object",
                    "example": {
                      "isDeleted": true,
                      "createdBy": "commodo minim dolore est",
                      "updatedBy": "dolor quis nulla",
                      "updatedDate": "1950-01-23T19:52:29.659Z",
                      "createdDate": "1950-01-23T19:52:29.659Z"
                    },
                    "additionalProperties": true,
                    "required": [
                      "isDeleted",
                      "createdBy",
                      "updatedBy",
                      "updatedDate",
                      "createdDate"
                    ],
                    "properties": {
                      "createdDate": {
                        "anyOf": [
                          {
                            "type": "string",
                            "format": "date-time"
                          },
                          {
                            "type": "null"
                          }
                        ],
                        "description": "Timestamp of when the entity was created"
                      },
                      "createdBy": {
                        "type": "string",
                        "description": "Identifies the system or user which created the entity"
                      },
                      "updatedDate": {
                        "anyOf": [
                          {
                            "type": "string",
                            "format": "date-time"
                          },
                          {
                            "type": "null"
                          }
                        ],
                        "description": "Timestamp of when the entity was last updated"
                      },
                      "updatedBy": {
                        "type": "string",
                        "description": "Identifies the system or user which last updated the entity"
                      },
                      "isDeleted": {
                        "anyOf": [
                          {
                            "type": "boolean"
                          },
                          {
                            "type": "null"
                          }
                        ],
                        "description": "Indicates whether or not the entity has been soft-deleted"
                      }
                    }
                  }
                }
              }
            ]
          }
        },
        "translatedName": {
          "type": "string"
        },
        "auditInfo": {
          "description": "Defines standard system audit fields available for most types",
          "type": "object",
          "example": {
            "isDeleted": true,
            "createdBy": "commodo minim dolore est",
            "updatedBy": "dolor quis nulla",
            "updatedDate": "1950-01-23T19:52:29.659Z",
            "createdDate": "1950-01-23T19:52:29.659Z"
          },
          "additionalProperties": true,
          "required": [
            "isDeleted",
            "createdBy",
            "updatedBy",
            "updatedDate",
            "createdDate"
          ],
          "properties": {
            "createdDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was created"
            },
            "createdBy": {
              "type": "string",
              "description": "Identifies the system or user which created the entity"
            },
            "updatedDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was last updated"
            },
            "updatedBy": {
              "type": "string",
              "description": "Identifies the system or user which last updated the entity"
            },
            "isDeleted": {
              "anyOf": [
                {
                  "type": "boolean"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Indicates whether or not the entity has been soft-deleted"
            }
          }
        }
      }
    }
  }
}

=== suryan14k/jenkins-pipeline-shared-library/api/exchange_modules/org.mule.examples/accelerator-cim-produce-library/1.2.0/examples/ProductCatalogTranslationExample.json
{
  "id": "in ea eu",
  "translatedName": "dolor Duis Ut eiusmod",
  "productCatalog": [
    "in aliquip officia ex dolore"
  ],
  "auditInfo": {
    "isDeleted": true,
    "createdBy": "irure exercitation ipsum esse dolor",
    "updatedBy": "ea",
    "updatedDate": "1982-02-06T19:28:07.461Z",
    "createdDate": null
  }
}
