=== suryan14k/jenkins-pipeline-shared-library/api/exchange_modules/org.mule.examples/accelerator-cim-produce-library/1.2.0/jsonSchemas/ProductRelationshipTypeSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/ProductRelationshipType",
  "definitions": {
    "ProductRelationshipType": {
      "type": "object",
      "example": {
        "childProductRole": "dolore proident",
        "id": null,
        "parentProductRole": "aliquip",
        "auditInfo": {
          "isDeleted": false,
          "createdBy": "sunt ullamco adipisicing",
          "updatedBy": "veniam nisi reprehenderit ut",
          "updatedDate": "1961-07-24T11:51:55.026Z",
          "createdDate": null
        }
      },
      "additionalProperties": true,
      "required": [
        "childProductRole",
        "id",
        "parentProductRole"
      ],
      "properties": {
        "id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "parentProductRole": {
          "type": "string"
        },
        "childProductRole": {
          "type": "string"
        },
        "auditInfo": {
          "description": "Defines standard system audit fields available for most types",
          "type": "object",
          "example": {
            "isDeleted": true,
            "createdBy": "commodo minim dolore est",
            "updatedBy": "dolor quis nulla",
            "updatedDate": "1950-01-23T19:52:29.659Z",
            "createdDate": "1950-01-23T19:52:29.659Z"
          },
          "additionalProperties": true,
          "required": [
            "isDeleted",
            "createdBy",
            "updatedBy",
            "updatedDate",
            "createdDate"
          ],
          "properties": {
            "createdDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was created"
            },
            "createdBy": {
              "type": "string",
              "description": "Identifies the system or user which created the entity"
            },
            "updatedDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was last updated"
            },
            "updatedBy": {
              "type": "string",
              "description": "Identifies the system or user which last updated the entity"
            },
            "isDeleted": {
              "anyOf": [
                {
                  "type": "boolean"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Indicates whether or not the entity has been soft-deleted"
            }
          }
        }
      }
    }
  }
}

=== suryan14k/jenkins-pipeline-shared-library/api/exchange_modules/org.mule.examples/accelerator-cim-produce-library/1.3.0/examples/ProductRelationshipTypeExample.json
{
  "childProductRole": "ullamco",
  "id": "in aute ad cillum elit",
  "parentProductRole": "reprehenderit deserunt minim ad consectetur",
  "auditInfo": {
    "isDeleted": null,
    "createdBy": "sed ea",
    "updatedBy": "qui",
    "updatedDate": "1966-10-14T18:29:38.152Z",
    "createdDate": null
  }
}
