=== suryan14k/jenkins-pipeline-shared-library/api/exchange_modules/org.mule.examples/accelerator-cim-produce-library/1.2.0/jsonSchemas/PurchaseOrderItemSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/PurchaseOrderItem",
  "definitions": {
    "PurchaseOrderItem": {
      "type": "object",
      "example": {
        "id": null,
        "name": "sed adipisicing officia laboris ut",
        "code": "ut id sed",
        "quantity": null,
        "auditInfo": {
          "isDeleted": null,
          "createdBy": "in do ut elit",
          "updatedBy": "voluptate proident ea",
          "updatedDate": null,
          "createdDate": null
        },
        "unitPrice": 87807204.91342908
      },
      "additionalProperties": true,
      "required": [
        "id"
      ],
      "properties": {
        "id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "name": {
          "type": "string"
        },
        "code": {
          "type": "string"
        },
        "unitPrice": {
          "anyOf": [
            {
              "type": "number"
            },
            {
              "type": "null"
            }
          ]
        },
        "quantity": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "auditInfo": {
          "description": "Defines standard system audit fields available for most types",
          "type": "object",
          "example": {
            "isDeleted": true,
            "createdBy": "commodo minim dolore est",
            "updatedBy": "dolor quis nulla",
            "updatedDate": "1950-01-23T19:52:29.659Z",
            "createdDate": "1950-01-23T19:52:29.659Z"
          },
          "additionalProperties": true,
          "required": [
            "isDeleted",
            "createdBy",
            "updatedBy",
            "updatedDate",
            "createdDate"
          ],
          "properties": {
            "createdDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was created"
            },
            "createdBy": {
              "type": "string",
              "description": "Identifies the system or user which created the entity"
            },
            "updatedDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was last updated"
            },
            "updatedBy": {
              "type": "string",
              "description": "Identifies the system or user which last updated the entity"
            },
            "isDeleted": {
              "anyOf": [
                {
                  "type": "boolean"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Indicates whether or not the entity has been soft-deleted"
            }
          }
        }
      }
    }
  }
}

=== suryan14k/jenkins-pipeline-shared-library/api/exchange_modules/org.mule.examples/accelerator-cim-produce-library/1.3.0/examples/PurchaseOrderItemExample.json
{
  "id": null,
  "quantity": 98443395,
  "unitPrice": 15680819.753759414,
  "code": "Excepteur reprehenderit velit culpa",
  "auditInfo": {
    "isDeleted": true,
    "createdBy": "sint nulla",
    "updatedBy": "irure ut dolore fugiat Duis",
    "updatedDate": null,
    "createdDate": "1970-08-16T15:28:08.389Z"
  },
  "name": "magna"
}
