=== suryan14k/jenkins-pipeline-shared-library/api/exchange_modules/org.mule.examples/accelerator-cim-sell-library/1.2.0/jsonSchemas/OrderDeliveryMethodSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/OrderDeliveryMethod",
  "definitions": {
    "OrderDeliveryMethod": {
      "type": "object",
      "example": {
        "name": "in eu",
        "id": "nulla sunt dolor sint pariatur",
        "auditInfo": {
          "isDeleted": true,
          "createdBy": "commodo magna laboris cillum Duis",
          "updatedBy": "ut amet Ut",
          "updatedDate": null,
          "createdDate": "1987-05-30T04:35:16.326Z"
        },
        "externalRecord": "laboris est",
        "product": [
          "Lorem incididunt magna"
        ]
      },
      "additionalProperties": true,
      "required": [
        "name",
        "id"
      ],
      "properties": {
        "id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "name": {
          "type": "string"
        },
        "product": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "externalRecord": {
          "type": "string"
        },
        "auditInfo": {
          "description": "Defines standard system audit fields available for most types",
          "type": "object",
          "example": {
            "isDeleted": true,
            "createdBy": "commodo minim dolore est",
            "updatedBy": "dolor quis nulla",
            "updatedDate": "1950-01-23T19:52:29.659Z",
            "createdDate": "1950-01-23T19:52:29.659Z"
          },
          "additionalProperties": true,
          "required": [
            "isDeleted",
            "createdBy",
            "updatedBy",
            "updatedDate",
            "createdDate"
          ],
          "properties": {
            "createdDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was created"
            },
            "createdBy": {
              "type": "string",
              "description": "Identifies the system or user which created the entity"
            },
            "updatedDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was last updated"
            },
            "updatedBy": {
              "type": "string",
              "description": "Identifies the system or user which last updated the entity"
            },
            "isDeleted": {
              "anyOf": [
                {
                  "type": "boolean"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Indicates whether or not the entity has been soft-deleted"
            }
          }
        }
      }
    }
  }
}

=== suryan14k/jenkins-pipeline-shared-library/api/exchange_modules/org.mule.examples/accelerator-cim-sell-library/1.2.0/examples/OrderDeliveryMethodExample.json
{
  "name": "dolor tempor laboris nulla amet",
  "id": null,
  "product": [
    "velit dolor est Duis"
  ],
  "auditInfo": {
    "isDeleted": null,
    "createdBy": "deserunt laboris sit",
    "updatedBy": "nostrud",
    "updatedDate": "1964-07-14T03:23:53.188Z",
    "createdDate": null
  },
  "externalRecord": "qui aliquip Excepteur consectetur"
}
