=== suryan14k/jenkins-pipeline-shared-library/api/exchange_modules/org.mule.examples/accelerator-cim-sell-library/1.2.0/jsonSchemas/SalesOrderDeliveryGroupSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/SalesOrderDeliveryGroup",
  "definitions": {
    "SalesOrderDeliveryGroup": {
      "type": "object",
      "example": {
        "name": "cillum quis",
        "id": null,
        "totalUnitPriceAmount": -20457491,
        "totalPriceAmount": null,
        "salesOrderDeliveryGroupNumber": "pariatur",
        "description": "qui pariatur commodo",
        "isGift": true,
        "salesOrderDeliveryStatus": [
          "Ut",
          "sed"
        ],
        "totalDeliveryChargeTaxAmount": -35362649,
        "totalDeliveryAdjustmentAmount": null,
        "totalDeliveryTaxAmount": null,
        "grandTotalDeliveryAmount": -88310989,
        "promisedDate": "1981-09-10",
        "deliveryInstructionsText": "voluptate non sed minim Excepteur",
        "contactPointAddress": [
          "Duis elit ad officia ex",
          "quis"
        ],
        "giftMessageText": "cillum",
        "accountContact": [
          "ex",
          "voluptate"
        ],
        "auditInfo": {
          "isDeleted": true,
          "createdBy": "occaecat nostrud dolor",
          "updatedBy": "velit dolor",
          "updatedDate": "1968-11-10T01:31:46.23Z",
          "createdDate": null
        },
        "totalProductTaxAmount": null,
        "totalDeliveryAdjustmentTaxAmount": null,
        "orderDeliveryMethod": [
          {
            "id": "ut",
            "name": "magna ullamco qui aliquip voluptate",
            "externalRecord": "in"
          },
          "amet eiusmod Ut elit"
        ],
        "desiredDeliveryDate": null,
        "totalTaxAmount": null,
        "originalDeliveryGroup": [
          "enim dolor"
        ],
        "salesOrder": [
          "minim cillum ea",
          "voluptate nisi id et"
        ],
        "totalDeliveryChargeAmount": null
      },
      "additionalProperties": true,
      "required": [
        "name",
        "id",
        "totalUnitPriceAmount",
        "totalPriceAmount",
        "salesOrderDeliveryGroupNumber",
        "description"
      ],
      "properties": {
        "id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "name": {
          "type": "string"
        },
        "totalPriceAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "totalDeliveryAdjustmentTaxAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "promisedDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "null"
            }
          ]
        },
        "giftMessageText": {
          "type": "string"
        },
        "deliveryInstructionsText": {
          "type": "string"
        },
        "totalProductTaxAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "totalDeliveryChargeAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "description": {
          "type": "string"
        },
        "grandTotalDeliveryAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "contactPointAddress": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "salesOrder": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "isGift": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        },
        "salesOrderDeliveryStatus": {
          "type": "array",
          "items": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "object",
                "additionalProperties": true,
                "required": [
                  "id",
                  "name"
                ],
                "properties": {
                  "id": {
                    "anyOf": [
                      {
                        "type": "string"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "name": {
                    "type": "string"
                  },
                  "auditInfo": {
                    "description": "Defines standard system audit fields available for most types",
                    "type": "object",
                    "example": {
                      "isDeleted": true,
                      "createdBy": "commodo minim dolore est",
                      "updatedBy": "dolor quis nulla",
                      "updatedDate": "1950-01-23T19:52:29.659Z",
                      "createdDate": "1950-01-23T19:52:29.659Z"
                    },
                    "additionalProperties": true,
                    "required": [
                      "isDeleted",
                      "createdBy",
                      "updatedBy",
                      "updatedDate",
                      "createdDate"
                    ],
                    "properties": {
                      "createdDate": {
                        "anyOf": [
                          {
                            "type": "string",
                            "format": "date-time"
                          },
                          {
                            "type": "null"
                          }
                        ],
                        "description": "Timestamp of when the entity was created"
                      },
                      "createdBy": {
                        "type": "string",
                        "description": "Identifies the system or user which created the entity"
                      },
                      "updatedDate": {
                        "anyOf": [
                          {
                            "type": "string",
                            "format": "date-time"
                          },
                          {
                            "type": "null"
                          }
                        ],
                        "description": "Timestamp of when the entity was last updated"
                      },
                      "updatedBy": {
                        "type": "string",
                        "description": "Identifies the system or user which last updated the entity"
                      },
                      "isDeleted": {
                        "anyOf": [
                          {
                            "type": "boolean"
                          },
                          {
                            "type": "null"
                          }
                        ],
                        "description": "Indicates whether or not the entity has been soft-deleted"
                      }
                    }
                  }
                }
              }
            ]
          }
        },
        "totalDeliveryAdjustmentAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "totalDeliveryTaxAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "totalTaxAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "totalDeliveryChargeTaxAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "originalDeliveryGroup": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "salesOrderDeliveryGroupNumber": {
          "type": "string"
        },
        "desiredDeliveryDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "null"
            }
          ]
        },
        "totalUnitPriceAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "orderDeliveryMethod": {
          "type": "array",
          "items": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "object",
                "additionalProperties": true,
                "required": [
                  "id",
                  "name"
                ],
                "properties": {
                  "id": {
                    "anyOf": [
                      {
                        "type": "string"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "name": {
                    "type": "string"
                  },
                  "product": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  },
                  "externalRecord": {
                    "type": "string"
                  },
                  "auditInfo": {
                    "description": "Defines standard system audit fields available for most types",
                    "type": "object",
                    "example": {
                      "isDeleted": true,
                      "createdBy": "commodo minim dolore est",
                      "updatedBy": "dolor quis nulla",
                      "updatedDate": "1950-01-23T19:52:29.659Z",
                      "createdDate": "1950-01-23T19:52:29.659Z"
                    },
                    "additionalProperties": true,
                    "required": [
                      "isDeleted",
                      "createdBy",
                      "updatedBy",
                      "updatedDate",
                      "createdDate"
                    ],
                    "properties": {
                      "createdDate": {
                        "anyOf": [
                          {
                            "type": "string",
                            "format": "date-time"
                          },
                          {
                            "type": "null"
                          }
                        ],
                        "description": "Timestamp of when the entity was created"
                      },
                      "createdBy": {
                        "type": "string",
                        "description": "Identifies the system or user which created the entity"
                      },
                      "updatedDate": {
                        "anyOf": [
                          {
                            "type": "string",
                            "format": "date-time"
                          },
                          {
                            "type": "null"
                          }
                        ],
                        "description": "Timestamp of when the entity was last updated"
                      },
                      "updatedBy": {
                        "type": "string",
                        "description": "Identifies the system or user which last updated the entity"
                      },
                      "isDeleted": {
                        "anyOf": [
                          {
                            "type": "boolean"
                          },
                          {
                            "type": "null"
                          }
                        ],
                        "description": "Indicates whether or not the entity has been soft-deleted"
                      }
                    }
                  }
                }
              }
            ]
          }
        },
        "accountContact": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "auditInfo": {
          "description": "Defines standard system audit fields available for most types",
          "type": "object",
          "example": {
            "isDeleted": true,
            "createdBy": "commodo minim dolore est",
            "updatedBy": "dolor quis nulla",
            "updatedDate": "1950-01-23T19:52:29.659Z",
            "createdDate": "1950-01-23T19:52:29.659Z"
          },
          "additionalProperties": true,
          "required": [
            "isDeleted",
            "createdBy",
            "updatedBy",
            "updatedDate",
            "createdDate"
          ],
          "properties": {
            "createdDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was created"
            },
            "createdBy": {
              "type": "string",
              "description": "Identifies the system or user which created the entity"
            },
            "updatedDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was last updated"
            },
            "updatedBy": {
              "type": "string",
              "description": "Identifies the system or user which last updated the entity"
            },
            "isDeleted": {
              "anyOf": [
                {
                  "type": "boolean"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Indicates whether or not the entity has been soft-deleted"
            }
          }
        }
      }
    }
  }
}

=== suryan14k/jenkins-pipeline-shared-library/api/exchange_modules/org.mule.examples/accelerator-cim-sell-library/1.2.0/examples/SalesOrderDeliveryGroupExample.json
{
  "name": "irure in tempor do sed",
  "id": "eu nostrud ipsum consequat",
  "totalUnitPriceAmount": null,
  "totalPriceAmount": -60215572,
  "salesOrderDeliveryGroupNumber": "eu ut elit",
  "description": "consequat",
  "salesOrderDeliveryStatus": [
    {
      "id": "sit in sed ex dolore",
      "name": "Lorem ullamco",
      "auditInfo": {
        "isDeleted": null,
        "createdBy": "proident dolore consequat Lorem",
        "updatedBy": "pariatur voluptate fugiat adipisicing in",
        "updatedDate": null,
        "createdDate": null
      }
    }
  ],
  "deliveryInstructionsText": "non aute anim Excepteur",
  "salesOrder": [
    "Duis"
  ],
  "totalTaxAmount": null,
  "orderDeliveryMethod": [
    "veniam nulla mollit pariatur exercitation"
  ],
  "totalDeliveryAdjustmentAmount": null,
  "promisedDate": "1985-03-16",
  "totalProductTaxAmount": null,
  "totalDeliveryTaxAmount": 63935123,
  "isGift": null,
  "giftMessageText": "laboris aute",
  "contactPointAddress": [
    "sunt"
  ],
  "totalDeliveryAdjustmentTaxAmount": null,
  "originalDeliveryGroup": [
    "eu"
  ],
  "accountContact": [
    "elit"
  ],
  "totalDeliveryChargeAmount": null,
  "totalDeliveryChargeTaxAmount": 96395408,
  "grandTotalDeliveryAmount": -50140200,
  "desiredDeliveryDate": null,
  "auditInfo": {
    "isDeleted": null,
    "createdBy": "aute adipisicing id",
    "updatedBy": "mollit voluptate nulla anim laborum",
    "updatedDate": null,
    "createdDate": "2008-07-26T00:11:16.038Z"
  }
}
