=== suryan14k/jenkins-pipeline-shared-library/api/exchange_modules/org.mule.examples/accelerator-cim-finance-library/1.2.0/jsonSchemas/PaymentCardSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/PaymentCard",
  "definitions": {
    "PaymentCard": {
      "type": "object",
      "example": {
        "paymentCardType": "amet Ut dolore",
        "name": "voluptate labore anim",
        "id": "do",
        "cardHolderName": "veniam",
        "paymentMethodStatus": "mollit irure",
        "expirationYear": "aliqua in do",
        "expirationMonth": "ipsum",
        "numberLastDigits": "reprehenderit velit pariatur sunt",
        "maskedNumber": "do reprehenderit laborum",
        "issueNumber": "in officia",
        "cardToken": "Duis reprehenderit",
        "billToLastName": "Duis",
        "derivedCardTypeCode": "dolore culpa",
        "billToCity": "cupidatat minim nostrud dolor",
        "billToStreet2": "exercitation consectetur aliqua qui",
        "companyName": "sunt deserunt",
        "billToFirstName": "veniam nulla deserunt culpa irure",
        "billToStreet": "Duis enim sed ut",
        "auditInfo": {
          "isDeleted": false,
          "createdBy": "aute dolore",
          "updatedBy": "laboris",
          "updatedDate": "1989-03-07T05:51:59.946Z",
          "createdDate": "1984-12-29T06:05:49.102Z"
        },
        "creditCardExpired": null,
        "paymentMethodType": [
          {
            "id": "laborum in aliqua",
            "typeRequiredIdentification": "laboris",
            "auditInfo": {
              "isDeleted": null,
              "createdBy": "laboris",
              "updatedBy": "reprehenderit veniam ut ullamco ut",
              "updatedDate": "1968-11-17T03:28:53.052Z",
              "createdDate": "1969-10-13T14:25:21.879Z"
            },
            "useMinimumAgeYear": null
          }
        ]
      },
      "additionalProperties": true,
      "required": [
        "paymentCardType",
        "name",
        "id",
        "cardHolderName",
        "paymentMethodStatus",
        "expirationYear",
        "expirationMonth",
        "numberLastDigits",
        "maskedNumber",
        "issueNumber",
        "cardToken"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "creditCardExpired": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        },
        "cardToken": {
          "type": "string"
        },
        "issueNumber": {
          "type": "string"
        },
        "billToCity": {
          "type": "string"
        },
        "maskedNumber": {
          "type": "string"
        },
        "companyName": {
          "type": "string"
        },
        "cardHolderName": {
          "type": "string"
        },
        "numberLastDigits": {
          "type": "string"
        },
        "paymentCardType": {
          "type": "string"
        },
        "derivedCardTypeCode": {
          "type": "string"
        },
        "billToFirstName": {
          "type": "string"
        },
        "billToStreet": {
          "type": "string"
        },
        "expirationYear": {
          "type": "string"
        },
        "billToStreet2": {
          "type": "string"
        },
        "expirationMonth": {
          "type": "string"
        },
        "billToLastName": {
          "type": "string"
        },
        "id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "paymentMethodType": {
          "type": "array",
          "items": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "object",
                "additionalProperties": true,
                "required": [
                  "id"
                ],
                "properties": {
                  "id": {
                    "anyOf": [
                      {
                        "type": "string"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "name": {
                    "type": "string"
                  },
                  "typeDescription": {
                    "type": "string"
                  },
                  "mediaType": {
                    "type": "string"
                  },
                  "maxPerPeriodAmount": {
                    "anyOf": [
                      {
                        "type": "integer"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "typeRequiredIdentification": {
                    "type": "string"
                  },
                  "useMinimumAgeYear": {
                    "anyOf": [
                      {
                        "type": "integer"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "maxTransactionAmount": {
                    "anyOf": [
                      {
                        "type": "integer"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "maxPerPeriodTransactionCount": {
                    "anyOf": [
                      {
                        "type": "integer"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "auditInfo": {
                    "description": "Defines standard system audit fields available for most types",
                    "type": "object",
                    "example": {
                      "isDeleted": true,
                      "createdBy": "commodo minim dolore est",
                      "updatedBy": "dolor quis nulla",
                      "updatedDate": "1950-01-23T19:52:29.659Z",
                      "createdDate": "1950-01-23T19:52:29.659Z"
                    },
                    "additionalProperties": true,
                    "required": [
                      "isDeleted",
                      "createdBy",
                      "updatedBy",
                      "updatedDate",
                      "createdDate"
                    ],
                    "properties": {
                      "createdDate": {
                        "anyOf": [
                          {
                            "type": "string",
                            "format": "date-time"
                          },
                          {
                            "type": "null"
                          }
                        ],
                        "description": "Timestamp of when the entity was created"
                      },
                      "createdBy": {
                        "type": "string",
                        "description": "Identifies the system or user which created the entity"
                      },
                      "updatedDate": {
                        "anyOf": [
                          {
                            "type": "string",
                            "format": "date-time"
                          },
                          {
                            "type": "null"
                          }
                        ],
                        "description": "Timestamp of when the entity was last updated"
                      },
                      "updatedBy": {
                        "type": "string",
                        "description": "Identifies the system or user which last updated the entity"
                      },
                      "isDeleted": {
                        "anyOf": [
                          {
                            "type": "boolean"
                          },
                          {
                            "type": "null"
                          }
                        ],
                        "description": "Indicates whether or not the entity has been soft-deleted"
                      }
                    }
                  }
                }
              }
            ]
          }
        },
        "paymentMethodStatus": {
          "type": "string"
        },
        "auditInfo": {
          "description": "Defines standard system audit fields available for most types",
          "type": "object",
          "example": {
            "isDeleted": true,
            "createdBy": "commodo minim dolore est",
            "updatedBy": "dolor quis nulla",
            "updatedDate": "1950-01-23T19:52:29.659Z",
            "createdDate": "1950-01-23T19:52:29.659Z"
          },
          "additionalProperties": true,
          "required": [
            "isDeleted",
            "createdBy",
            "updatedBy",
            "updatedDate",
            "createdDate"
          ],
          "properties": {
            "createdDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was created"
            },
            "createdBy": {
              "type": "string",
              "description": "Identifies the system or user which created the entity"
            },
            "updatedDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was last updated"
            },
            "updatedBy": {
              "type": "string",
              "description": "Identifies the system or user which last updated the entity"
            },
            "isDeleted": {
              "anyOf": [
                {
                  "type": "boolean"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Indicates whether or not the entity has been soft-deleted"
            }
          }
        }
      }
    }
  }
}

=== suryan14k/jenkins-pipeline-shared-library/api/exchange_modules/org.mule.examples/accelerator-cim-finance-library/1.2.0/examples/PaymentCardExample.json
{
  "paymentCardType": "aliquip deserunt Ut sunt",
  "name": "magna officia",
  "id": "Excepteur quis",
  "cardHolderName": "labore Excepteur",
  "paymentMethodStatus": "esse consequat anim Ut exercitation",
  "expirationYear": "nulla",
  "expirationMonth": "sed",
  "numberLastDigits": "deserunt",
  "maskedNumber": "proident dolore est nisi",
  "issueNumber": "ullamco eu",
  "cardToken": "culpa nulla dolore",
  "billToStreet2": "exercitation commodo Duis dolor",
  "billToLastName": "velit quis adipisicing tempor",
  "paymentMethodType": [
    {
      "id": "adipisicing sint sunt",
      "maxPerPeriodAmount": null,
      "name": "ipsum",
      "mediaType": "culpa",
      "maxPerPeriodTransactionCount": 20341621,
      "maxTransactionAmount": 56400001,
      "auditInfo": {
        "isDeleted": true,
        "createdBy": "ullamco nisi id",
        "updatedBy": "deserunt",
        "updatedDate": "1950-08-03T04:56:48.456Z",
        "createdDate": null
      },
      "typeDescription": "ea in sint eu",
      "typeRequiredIdentification": "aliquip est"
    }
  ],
  "billToFirstName": "ut est velit",
  "companyName": "tempor nisi in in",
  "creditCardExpired": null,
  "billToCity": "dolore consectetur Ut nulla",
  "auditInfo": {
    "isDeleted": null,
    "createdBy": "cupidatat",
    "updatedBy": "dolore minim ut aliqua exercitation",
    "updatedDate": null,
    "createdDate": null
  },
  "billToStreet": "et",
  "derivedCardTypeCode": "ipsum occaecat"
}
