=== suryan14k/jenkins-pipeline-shared-library/api/exchange_modules/org.mule.examples/accelerator-cim-finance-library/1.2.0/jsonSchemas/PaymentTreatmentMethodSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/PaymentTreatmentMethod",
  "definitions": {
    "PaymentTreatmentMethod": {
      "type": "object",
      "example": {
        "paymentTreatmentMethodCode": "amet",
        "paymentTreatmentMethodName": "in adipisicing veniam culpa",
        "id": null,
        "paymentTreatmentMethodDescription": "culpa",
        "auditInfo": {
          "isDeleted": null,
          "createdBy": "Lorem eu",
          "updatedBy": "nisi deserunt veniam",
          "updatedDate": "1982-05-08T03:20:14.574Z",
          "createdDate": "2020-08-03T00:44:34.105Z"
        }
      },
      "additionalProperties": true,
      "required": [
        "paymentTreatmentMethodCode",
        "paymentTreatmentMethodName",
        "id",
        "paymentTreatmentMethodDescription"
      ],
      "properties": {
        "id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "paymentTreatmentMethodName": {
          "type": "string"
        },
        "paymentTreatmentMethodCode": {
          "type": "string"
        },
        "paymentTreatmentMethodDescription": {
          "type": "string"
        },
        "auditInfo": {
          "description": "Defines standard system audit fields available for most types",
          "type": "object",
          "example": {
            "isDeleted": true,
            "createdBy": "commodo minim dolore est",
            "updatedBy": "dolor quis nulla",
            "updatedDate": "1950-01-23T19:52:29.659Z",
            "createdDate": "1950-01-23T19:52:29.659Z"
          },
          "additionalProperties": true,
          "required": [
            "isDeleted",
            "createdBy",
            "updatedBy",
            "updatedDate",
            "createdDate"
          ],
          "properties": {
            "createdDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was created"
            },
            "createdBy": {
              "type": "string",
              "description": "Identifies the system or user which created the entity"
            },
            "updatedDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was last updated"
            },
            "updatedBy": {
              "type": "string",
              "description": "Identifies the system or user which last updated the entity"
            },
            "isDeleted": {
              "anyOf": [
                {
                  "type": "boolean"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Indicates whether or not the entity has been soft-deleted"
            }
          }
        }
      }
    }
  }
}

=== suryan14k/jenkins-pipeline-shared-library/api/exchange_modules/org.mule.examples/accelerator-cim-finance-library/1.2.0/examples/PaymentTreatmentMethodExample.json
{
  "paymentTreatmentMethodCode": "Lorem in do ipsum",
  "paymentTreatmentMethodName": "pariatur",
  "id": null,
  "paymentTreatmentMethodDescription": "dolor tempor eiusmod eu",
  "auditInfo": {
    "isDeleted": false,
    "createdBy": "ut cillum in cupidatat",
    "updatedBy": "sint",
    "updatedDate": "2000-08-01T09:05:33.634Z",
    "createdDate": null
  }
}
