=== suryan14k/jenkins-pipeline-shared-library/api/exchange_modules/org.mule.examples/accelerator-cim-finance-library/1.2.0/jsonSchemas/PaymentPolicySchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/PaymentPolicy",
  "definitions": {
    "PaymentPolicy": {
      "type": "object",
      "example": {
        "name": "ut do sed sunt amet",
        "id": "magna est",
        "paymentPolicyStatus": "mollit in aute",
        "description": "ut in",
        "auditInfo": {
          "isDeleted": null,
          "createdBy": "veniam sed et adipisicing labore",
          "updatedBy": "ea voluptate enim",
          "updatedDate": null,
          "createdDate": null
        },
        "paymentPolicyTreatmentSelection": "in et"
      },
      "additionalProperties": true,
      "required": [
        "name",
        "id",
        "paymentPolicyStatus",
        "description"
      ],
      "properties": {
        "id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "name": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "paymentPolicyTreatmentSelection": {
          "type": "string"
        },
        "paymentPolicyStatus": {
          "type": "string"
        },
        "auditInfo": {
          "description": "Defines standard system audit fields available for most types",
          "type": "object",
          "example": {
            "isDeleted": true,
            "createdBy": "commodo minim dolore est",
            "updatedBy": "dolor quis nulla",
            "updatedDate": "1950-01-23T19:52:29.659Z",
            "createdDate": "1950-01-23T19:52:29.659Z"
          },
          "additionalProperties": true,
          "required": [
            "isDeleted",
            "createdBy",
            "updatedBy",
            "updatedDate",
            "createdDate"
          ],
          "properties": {
            "createdDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was created"
            },
            "createdBy": {
              "type": "string",
              "description": "Identifies the system or user which created the entity"
            },
            "updatedDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was last updated"
            },
            "updatedBy": {
              "type": "string",
              "description": "Identifies the system or user which last updated the entity"
            },
            "isDeleted": {
              "anyOf": [
                {
                  "type": "boolean"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Indicates whether or not the entity has been soft-deleted"
            }
          }
        }
      }
    }
  }
}

=== suryan14k/jenkins-pipeline-shared-library/api/exchange_modules/org.mule.examples/accelerator-cim-finance-library/1.2.0/examples/PaymentPolicyExample.json
{
  "name": "qui non Lorem adipisicing do",
  "id": null,
  "paymentPolicyStatus": "adipisicing elit reprehenderit cillum",
  "description": "in tempor nisi",
  "paymentPolicyTreatmentSelection": "esse ut ipsum",
  "auditInfo": {
    "isDeleted": false,
    "createdBy": "quis esse ex est",
    "updatedBy": "sunt ut sint mollit veniam",
    "updatedDate": null,
    "createdDate": "1964-02-12T00:06:36.97Z"
  }
}
