=== suryan14k/jenkins-pipeline-shared-library/api/exchange_modules/org.mule.examples/accelerator-cim-finance-library/1.2.0/jsonSchemas/PaymentGatewayInteractionLogSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/PaymentGatewayInteractionLog",
  "definitions": {
    "PaymentGatewayInteractionLog": {
      "type": "object",
      "example": {
        "internalReferenceNumber": "occaecat ea Excepteur ad sed",
        "paymentGatewayDate": "1942-07-11",
        "paymentGatewayInteractionType": [
          "do anim elit dolore id",
          "ullamco nisi magna qui eiusmod"
        ],
        "id": null,
        "paymentGatewayResult": [
          "quis mollit"
        ],
        "paymentGatewayInteractionLogName": "sed",
        "paymentGatewayInteractionStatus": "aute consectetur",
        "paymentGatewayAuthorizationCode": "adipisicing mollit id reprehenderit incididunt",
        "name": "enim Ut labore sint ex",
        "internalResultCode": "ut",
        "auditInfo": {
          "isDeleted": null,
          "createdBy": "eu mollit",
          "updatedBy": "exercitation do quis mollit",
          "updatedDate": null,
          "createdDate": null
        },
        "paymentGatewayReferenceNumber": "officia",
        "paymentGatewayAVSCode": "dolor sunt do minim",
        "paymentGatewayMessageText": "sed"
      },
      "additionalProperties": true,
      "required": [
        "internalReferenceNumber",
        "paymentGatewayDate",
        "paymentGatewayInteractionType",
        "id",
        "paymentGatewayResult",
        "paymentGatewayInteractionLogName",
        "paymentGatewayInteractionStatus"
      ],
      "properties": {
        "id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "name": {
          "type": "string"
        },
        "paymentGatewayInteractionType": {
          "type": "array",
          "items": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "object",
                "additionalProperties": true,
                "required": [
                  "id",
                  "name",
                  "description"
                ],
                "properties": {
                  "id": {
                    "anyOf": [
                      {
                        "type": "string"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "name": {
                    "type": "string"
                  },
                  "description": {
                    "type": "string"
                  },
                  "auditInfo": {
                    "description": "Defines standard system audit fields available for most types",
                    "type": "object",
                    "example": {
                      "isDeleted": true,
                      "createdBy": "commodo minim dolore est",
                      "updatedBy": "dolor quis nulla",
                      "updatedDate": "1950-01-23T19:52:29.659Z",
                      "createdDate": "1950-01-23T19:52:29.659Z"
                    },
                    "additionalProperties": true,
                    "required": [
                      "isDeleted",
                      "createdBy",
                      "updatedBy",
                      "updatedDate",
                      "createdDate"
                    ],
                    "properties": {
                      "createdDate": {
                        "anyOf": [
                          {
                            "type": "string",
                            "format": "date-time"
                          },
                          {
                            "type": "null"
                          }
                        ],
                        "description": "Timestamp of when the entity was created"
                      },
                      "createdBy": {
                        "type": "string",
                        "description": "Identifies the system or user which created the entity"
                      },
                      "updatedDate": {
                        "anyOf": [
                          {
                            "type": "string",
                            "format": "date-time"
                          },
                          {
                            "type": "null"
                          }
                        ],
                        "description": "Timestamp of when the entity was last updated"
                      },
                      "updatedBy": {
                        "type": "string",
                        "description": "Identifies the system or user which last updated the entity"
                      },
                      "isDeleted": {
                        "anyOf": [
                          {
                            "type": "boolean"
                          },
                          {
                            "type": "null"
                          }
                        ],
                        "description": "Indicates whether or not the entity has been soft-deleted"
                      }
                    }
                  }
                }
              }
            ]
          }
        },
        "paymentGatewayReferenceNumber": {
          "type": "string"
        },
        "paymentGatewayMessageText": {
          "type": "string"
        },
        "paymentGatewayAuthorizationCode": {
          "type": "string"
        },
        "internalResultCode": {
          "type": "string"
        },
        "paymentGatewayAVSCode": {
          "type": "string"
        },
        "internalReferenceNumber": {
          "type": "string"
        },
        "paymentGatewayResult": {
          "type": "array",
          "items": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "object",
                "additionalProperties": true,
                "required": [
                  "id",
                  "name",
                  "description"
                ],
                "properties": {
                  "id": {
                    "anyOf": [
                      {
                        "type": "string"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "name": {
                    "type": "string"
                  },
                  "description": {
                    "type": "string"
                  },
                  "auditInfo": {
                    "description": "Defines standard system audit fields available for most types",
                    "type": "object",
                    "example": {
                      "isDeleted": true,
                      "createdBy": "commodo minim dolore est",
                      "updatedBy": "dolor quis nulla",
                      "updatedDate": "1950-01-23T19:52:29.659Z",
                      "createdDate": "1950-01-23T19:52:29.659Z"
                    },
                    "additionalProperties": true,
                    "required": [
                      "isDeleted",
                      "createdBy",
                      "updatedBy",
                      "updatedDate",
                      "createdDate"
                    ],
                    "properties": {
                      "createdDate": {
                        "anyOf": [
                          {
                            "type": "string",
                            "format": "date-time"
                          },
                          {
                            "type": "null"
                          }
                        ],
                        "description": "Timestamp of when the entity was created"
                      },
                      "createdBy": {
                        "type": "string",
                        "description": "Identifies the system or user which created the entity"
                      },
                      "updatedDate": {
                        "anyOf": [
                          {
                            "type": "string",
                            "format": "date-time"
                          },
                          {
                            "type": "null"
                          }
                        ],
                        "description": "Timestamp of when the entity was last updated"
                      },
                      "updatedBy": {
                        "type": "string",
                        "description": "Identifies the system or user which last updated the entity"
                      },
                      "isDeleted": {
                        "anyOf": [
                          {
                            "type": "boolean"
                          },
                          {
                            "type": "null"
                          }
                        ],
                        "description": "Indicates whether or not the entity has been soft-deleted"
                      }
                    }
                  }
                }
              }
            ]
          }
        },
        "paymentGatewayInteractionLogName": {
          "type": "string"
        },
        "paymentGatewayInteractionStatus": {
          "type": "string"
        },
        "paymentGatewayDate": {
          "type": "string",
          "format": "date"
        },
        "auditInfo": {
          "description": "Defines standard system audit fields available for most types",
          "type": "object",
          "example": {
            "isDeleted": true,
            "createdBy": "commodo minim dolore est",
            "updatedBy": "dolor quis nulla",
            "updatedDate": "1950-01-23T19:52:29.659Z",
            "createdDate": "1950-01-23T19:52:29.659Z"
          },
          "additionalProperties": true,
          "required": [
            "isDeleted",
            "createdBy",
            "updatedBy",
            "updatedDate",
            "createdDate"
          ],
          "properties": {
            "createdDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was created"
            },
            "createdBy": {
              "type": "string",
              "description": "Identifies the system or user which created the entity"
            },
            "updatedDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was last updated"
            },
            "updatedBy": {
              "type": "string",
              "description": "Identifies the system or user which last updated the entity"
            },
            "isDeleted": {
              "anyOf": [
                {
                  "type": "boolean"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Indicates whether or not the entity has been soft-deleted"
            }
          }
        }
      }
    }
  }
}

=== suryan14k/jenkins-pipeline-shared-library/api/exchange_modules/org.mule.examples/accelerator-cim-finance-library/1.2.0/examples/PaymentGatewayInteractionLogExample.json
{
  "internalReferenceNumber": "occaecat dolor dolore",
  "paymentGatewayDate": "1971-01-02",
  "paymentGatewayInteractionType": [
    {
      "id": "elit officia",
      "name": "do Excepteur",
      "description": "reprehenderit ea",
      "auditInfo": {
        "isDeleted": true,
        "createdBy": "fugiat velit",
        "updatedBy": "labore",
        "updatedDate": "2003-01-24T00:58:29.335Z",
        "createdDate": null
      }
    }
  ],
  "id": "elit",
  "paymentGatewayResult": [
    {
      "id": null,
      "name": "officia pariatur ullamco Excepteur voluptate",
      "description": "minim pariatur laboris veniam sed",
      "auditInfo": {
        "isDeleted": false,
        "createdBy": "deserunt aliqua",
        "updatedBy": "cillum pariatur dolore adipisicing",
        "updatedDate": null,
        "createdDate": "1959-12-16T03:49:00.443Z"
      }
    }
  ],
  "paymentGatewayInteractionLogName": "qui nisi est",
  "paymentGatewayInteractionStatus": "adipisicing nisi",
  "paymentGatewayMessageText": "eiusmod",
  "paymentGatewayAVSCode": "id ea dolor occaecat",
  "name": "proident aute"
}
