=== suryan14k/jenkins-pipeline-shared-library/api/exchange_modules/org.mule.examples/accelerator-cim-finance-library/1.2.0/jsonSchemas/PaymentGroupSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/PaymentGroup",
  "definitions": {
    "PaymentGroup": {
      "type": "object",
      "example": {
        "paymentGroupNumber": "exercitation cupidatat eiusmod proident",
        "totalReversalAmount": -53045311,
        "id": null,
        "totalPaymentAmount": -34206398,
        "totalAuthorizationAmount": 35178903,
        "auditInfo": {
          "isDeleted": false,
          "createdBy": "deserunt eu sit consectetur",
          "updatedBy": "cillum",
          "updatedDate": null,
          "createdDate": null
        }
      },
      "additionalProperties": true,
      "required": [
        "paymentGroupNumber",
        "totalReversalAmount",
        "id",
        "totalPaymentAmount",
        "totalAuthorizationAmount"
      ],
      "properties": {
        "id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "totalReversalAmount": {
          "type": "integer"
        },
        "totalAuthorizationAmount": {
          "type": "integer"
        },
        "totalPaymentAmount": {
          "type": "integer"
        },
        "paymentGroupNumber": {
          "type": "string"
        },
        "auditInfo": {
          "description": "Defines standard system audit fields available for most types",
          "type": "object",
          "example": {
            "isDeleted": true,
            "createdBy": "commodo minim dolore est",
            "updatedBy": "dolor quis nulla",
            "updatedDate": "1950-01-23T19:52:29.659Z",
            "createdDate": "1950-01-23T19:52:29.659Z"
          },
          "additionalProperties": true,
          "required": [
            "isDeleted",
            "createdBy",
            "updatedBy",
            "updatedDate",
            "createdDate"
          ],
          "properties": {
            "createdDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was created"
            },
            "createdBy": {
              "type": "string",
              "description": "Identifies the system or user which created the entity"
            },
            "updatedDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was last updated"
            },
            "updatedBy": {
              "type": "string",
              "description": "Identifies the system or user which last updated the entity"
            },
            "isDeleted": {
              "anyOf": [
                {
                  "type": "boolean"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Indicates whether or not the entity has been soft-deleted"
            }
          }
        }
      }
    }
  }
}

=== suryan14k/jenkins-pipeline-shared-library/api/exchange_modules/org.mule.examples/accelerator-cim-finance-library/1.2.0/examples/PaymentGroupExample.json
{
  "paymentGroupNumber": "aute ut dolor",
  "totalReversalAmount": 70979013,
  "id": "magna enim",
  "totalPaymentAmount": 65140841,
  "totalAuthorizationAmount": 92343251,
  "auditInfo": {
    "isDeleted": null,
    "createdBy": "reprehenderit ea eiusmod incididunt",
    "updatedBy": "sed eu nisi minim",
    "updatedDate": null,
    "createdDate": "1967-04-30T17:25:11.128Z"
  }
}
