=== suryan14k/jenkins-pipeline-shared-library/api/exchange_modules/org.mule.examples/accelerator-cim-finance-library/1.2.0/jsonSchemas/PaymentMethodTypeSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/PaymentMethodType",
  "definitions": {
    "PaymentMethodType": {
      "type": "object",
      "example": {
        "id": "est Excepteur ipsum incididunt",
        "maxTransactionAmount": 37683405,
        "mediaType": "irure commodo aute do officia",
        "maxPerPeriodAmount": 30701420,
        "useMinimumAgeYear": -77780440,
        "maxPerPeriodTransactionCount": null,
        "typeRequiredIdentification": "magna officia tempor",
        "auditInfo": {
          "isDeleted": null,
          "createdBy": "dolor do consequat sunt in",
          "updatedBy": "laborum magna in ipsum",
          "updatedDate": null,
          "createdDate": "1954-02-20T13:42:12.026Z"
        },
        "typeDescription": "cupidatat occaecat reprehenderit",
        "name": "culpa"
      },
      "additionalProperties": true,
      "required": [
        "id"
      ],
      "properties": {
        "id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "name": {
          "type": "string"
        },
        "typeDescription": {
          "type": "string"
        },
        "mediaType": {
          "type": "string"
        },
        "maxPerPeriodAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "typeRequiredIdentification": {
          "type": "string"
        },
        "useMinimumAgeYear": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "maxTransactionAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "maxPerPeriodTransactionCount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "auditInfo": {
          "description": "Defines standard system audit fields available for most types",
          "type": "object",
          "example": {
            "isDeleted": true,
            "createdBy": "commodo minim dolore est",
            "updatedBy": "dolor quis nulla",
            "updatedDate": "1950-01-23T19:52:29.659Z",
            "createdDate": "1950-01-23T19:52:29.659Z"
          },
          "additionalProperties": true,
          "required": [
            "isDeleted",
            "createdBy",
            "updatedBy",
            "updatedDate",
            "createdDate"
          ],
          "properties": {
            "createdDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was created"
            },
            "createdBy": {
              "type": "string",
              "description": "Identifies the system or user which created the entity"
            },
            "updatedDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was last updated"
            },
            "updatedBy": {
              "type": "string",
              "description": "Identifies the system or user which last updated the entity"
            },
            "isDeleted": {
              "anyOf": [
                {
                  "type": "boolean"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Indicates whether or not the entity has been soft-deleted"
            }
          }
        }
      }
    }
  }
}

=== suryan14k/jenkins-pipeline-shared-library/api/exchange_modules/org.mule.examples/accelerator-cim-finance-library/1.2.0/examples/PaymentMethodTypeExample.json
{
  "id": "fugiat nulla eu",
  "maxPerPeriodTransactionCount": 34234684,
  "maxPerPeriodAmount": null,
  "mediaType": "anim qui eu cupidatat incididunt",
  "typeRequiredIdentification": "aliquip ea",
  "auditInfo": {
    "isDeleted": null,
    "createdBy": "officia",
    "updatedBy": "magna sed",
    "updatedDate": "1974-04-21T01:12:28.801Z",
    "createdDate": null
  },
  "maxTransactionAmount": -73508510,
  "useMinimumAgeYear": null,
  "name": "voluptate enim irure ut id"
}
